language: d
sudo: false

matrix:
    include:
        - d: dmd-2.088.1
        - d: dmd-2.087.1
        - d: dmd-2.086.1
        - d: dmd-2.085.1
        - d: dmd-2.084.1
        - d: dmd-2.083.1
        - d: dmd-2.082.1
        - d: dmd-2.081.2
        - d: dmd-2.080.1
        - d: dmd-2.079.0
        - d: ldc-1.18.0
        - d: ldc-1.17.0
        - d: ldc-1.16.0
        - d: ldc-1.15.0
        - d: ldc-1.14.0
        - d: ldc-1.13.0
        - d: ldc-1.12.0
        - d: ldc-1.11.0
        - d: ldc-1.10.0

script:
  - pushd examples/sdl  && dub build --compiler=${DC} && popd
  - pushd examples/arsd && dub build --compiler=${DC} && popd